#!/usr/bin/env node

const Docker = require("dockerode");
const blessed = require("blessed");
const { program } = require("commander");
const DockerLib = require("./docker.js");

program
	.description("Sort an array while you make coffee")
	.option("-i --input <input>", "Input array - '[1,2,3]'")
	.parse();

const options = program.opts();
const inputArray = JSON.parse(options.input);

const docker = new Docker();

DockerLib.build(docker).then(() => {
	const screen = blessed.screen({
		smartCSR: true,
		title: "Containers",
	});

	const itemsWithScores = inputArray.reduce((output, value) => {
		output.push({ value: value, score: 0 });
		return output;
	}, []);

	const outputPromises = itemsWithScores.map((itemWithScore, index) => {
		return DockerLib.run(docker, screen, index).then((score) => {
			itemWithScore.score = score;
		});
	});

	Promise.all(outputPromises).finally(() => {
		DockerLib.cleanOutputDir();
		screen.destroy();
		console.clear();
		itemsWithScores.sort((a, b) => b.score - a.score);
		console.log(itemsWithScores.map((item) => item.value));
	});
});
